# Generated by Django 5.0.3 on 2024-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('000', 'Base platform'), ('014', 'Bumper'), ('037', 'Drum Mulcher'), ('036', 'Side Trimmer'), ('038', 'Sprayer'), ('027', 'Lawn Mower')], max_length=3)),
                ('equipment_code', models.CharField(max_length=3)),
                ('year_of_issue', models.IntegerField()),
                ('serial_number', models.IntegerField()),
                ('place_of_production', models.CharField(choices=[('00', 'Slovenia'), ('01', 'Turkey')], max_length=2)),
            ],
        ),
    ]
