# Generated by Django 5.0.3 on 2024-03-06 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_vin_equipment_code_alter_vin_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='serial_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(1999999)]),
        ),
    ]
