# Generated by Django 5.0.3 on 2024-03-07 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_alter_vin_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='serial_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(999999), django.core.validators.MaxValueValidator(2000000)]),
        ),
    ]
