services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: vingeneratortesttask:django
    container_name: vingeneratortesttask
    command: python manage.py runserver 0.0.0.0:8000
